"""Curated learning resources for the adaptive-learning frontend."""

RESOURCES = [
    {
        "resource_id": "dsa-visualgo",
        "domain": "dsa",
        "topic_id": "dsa.visualization",
        "title": "VisuAlgo",
        "resource_type": "visualization",
        "level": "beginner-advanced",
        "duration": None,
        "url": "https://visualgo.net/",
        "can_embed": False,
    },
    {
        "resource_id": "dsa-beginner-video",
        "domain": "dsa",
        "topic_id": "dsa.fundamentals",
        "title": "Data Structures and Algorithms Introduction",
        "resource_type": "video",
        "level": "beginner",
        "duration": "10 min",
        "url": "https://youtu.be/3_x_Fb31NLE",
        "can_embed": True,
    },
    {
        "resource_id": "dsa-atcoder",
        "domain": "dsa",
        "topic_id": "dsa.practice",
        "title": "AtCoder Practice",
        "resource_type": "practice",
        "level": "intermediate-advanced",
        "duration": None,
        "url": "https://atcoder.jp/",
        "can_embed": False,
    },
    {
        "resource_id": "dsa-gfg-tutorial",
        "domain": "dsa",
        "topic_id": "dsa.fundamentals",
        "title": "GeeksforGeeks DSA Tutorial",
        "resource_type": "tutorial",
        "level": "beginner-intermediate",
        "duration": None,
        "url": "https://www.geeksforgeeks.org/dsa/learn-data-structures-and-algorithms-dsa-tutorial/",
        "can_embed": False,
    },
    {
        "resource_id": "dsa-hackerrank",
        "domain": "dsa",
        "topic_id": "dsa.practice",
        "title": "HackerRank Data Structures",
        "resource_type": "practice",
        "level": "beginner-intermediate",
        "duration": None,
        "url": "https://www.hackerrank.com/domains/data-structures",
        "can_embed": False,
    },
    {
        "resource_id": "dsa-leetcode-learn",
        "domain": "dsa",
        "topic_id": "dsa.practice",
        "title": "LeetCode Learn",
        "resource_type": "course",
        "level": "beginner-intermediate",
        "duration": "2 hours",
        "url": "https://leetcode.com/explore/learn/",
        "can_embed": False,
    },
    {
        "resource_id": "dsa-dp-gfg",
        "domain": "dsa",
        "topic_id": "dsa.dynamic-programming",
        "title": "Dynamic Programming Tutorial",
        "resource_type": "article",
        "level": "beginner-advanced",
        "duration": None,
        "url": "https://www.geeksforgeeks.org/dsa/dynamic-programming/",
        "can_embed": False,
    },
    {
        "resource_id": "dsa-dp-tuf",
        "domain": "dsa",
        "topic_id": "dsa.dynamic-programming",
        "title": "Take U Forward Dynamic Programming",
        "resource_type": "tutorial",
        "level": "intermediate-advanced",
        "duration": None,
        "url": "https://takeuforward.org/plus/dsa/dynamic-programming",
        "can_embed": False,
    },
    {
        "resource_id": "dsa-dp-leetcode",
        "domain": "dsa",
        "topic_id": "dsa.dynamic-programming",
        "title": "LeetCode Dynamic Programming Problems",
        "resource_type": "practice",
        "level": "intermediate-advanced",
        "duration": None,
        "url": "https://leetcode.com/problem-list/dynamic-programming/",
        "can_embed": False,
    },
    {
        "resource_id": "dsa-recursion-gfg",
        "domain": "dsa",
        "topic_id": "dsa.recursion",
        "title": "Recursion Tutorial",
        "resource_type": "article",
        "level": "beginner-intermediate",
        "duration": None,
        "url": "https://www.geeksforgeeks.org/dsa/recursion/",
        "can_embed": False,
    },
    {
        "resource_id": "dsa-binary-search-tuf",
        "domain": "dsa",
        "topic_id": "dsa.binary-search",
        "title": "Take U Forward Binary Search",
        "resource_type": "tutorial",
        "level": "beginner-intermediate",
        "duration": None,
        "url": "https://takeuforward.org/plus/dsa/binary-search",
        "can_embed": False,
    },
    {
        "resource_id": "dsa-strivers-roadmap",
        "domain": "dsa",
        "topic_id": "dsa.roadmap",
        "title": "Striver's A2Z DSA Sheet",
        "resource_type": "roadmap",
        "level": "beginner-advanced",
        "duration": None,
        "url": "https://takeuforward.org/prep-hub/strivers-a2z-dsa-sheet",
        "can_embed": False,
    },
    {
        "resource_id": "dsa-neetcode-roadmap",
        "domain": "dsa",
        "topic_id": "dsa.roadmap",
        "title": "NeetCode Roadmap",
        "resource_type": "roadmap",
        "level": "beginner-advanced",
        "duration": None,
        "url": "https://neetcode.io/roadmap",
        "can_embed": False,
    },
    {
        "resource_id": "dbms-sql-tutorial",
        "domain": "dbms",
        "topic_id": "dbms.sql",
        "title": "SQL Tutorial",
        "resource_type": "tutorial",
        "level": "beginner-intermediate",
        "duration": None,
        "url": "https://www.geeksforgeeks.org/sql/sql-tutorial/",
        "can_embed": False,
    },
    {
        "resource_id": "dbms-introduction-video",
        "domain": "dbms",
        "topic_id": "dbms.fundamentals",
        "title": "DBMS Full Course",
        "resource_type": "video",
        "level": "beginner",
        "duration": "5 hours",
        "url": "https://www.youtube.com/watch?v=HXV3zeQKqGY",
        "can_embed": True,
    },
    {
        "resource_id": "dbms-normalization",
        "domain": "dbms",
        "topic_id": "dbms.normalization",
        "title": "Database Normalization",
        "resource_type": "article",
        "level": "beginner-intermediate",
        "duration": None,
        "url": "https://www.geeksforgeeks.org/dbms/introduction-of-database-normalization/",
        "can_embed": False,
    },
    {
        "resource_id": "dbms-acid-video",
        "domain": "dbms",
        "topic_id": "dbms.transactions",
        "title": "ACID Properties",
        "resource_type": "video",
        "level": "beginner-intermediate",
        "duration": "5 min",
        "url": "https://www.youtube.com/watch?v=GAe5oB742dw",
        "can_embed": True,
    },
    {
        "resource_id": "dbms-joins",
        "domain": "dbms",
        "topic_id": "dbms.joins",
        "title": "SQL Joins",
        "resource_type": "article",
        "level": "beginner-intermediate",
        "duration": None,
        "url": "https://www.geeksforgeeks.org/sql/sql-join-set-1-inner-left-right-and-full-joins/",
        "can_embed": False,
    },
    {
        "resource_id": "dbms-postgresql",
        "domain": "dbms",
        "topic_id": "dbms.sql",
        "title": "PostgreSQL Tutorial",
        "resource_type": "documentation",
        "level": "beginner-intermediate",
        "duration": None,
        "url": "https://www.postgresql.org/docs/current/tutorial.html",
        "can_embed": False,
    },
    {
        "resource_id": "system-design-video",
        "domain": "system_design",
        "topic_id": "system-design.fundamentals",
        "title": "System Design Fundamentals",
        "resource_type": "video",
        "level": "beginner-intermediate",
        "duration": "1.5 hours",
        "url": "https://www.youtube.com/watch?v=bUHFg8CZFws",
        "can_embed": True,
    },
    {
        "resource_id": "system-design-gfg",
        "domain": "system_design",
        "topic_id": "system-design.fundamentals",
        "title": "System Design Tutorial",
        "resource_type": "tutorial",
        "level": "beginner-advanced",
        "duration": None,
        "url": "https://www.geeksforgeeks.org/system-design/system-design-tutorial/",
        "can_embed": False,
    },
    {
        "resource_id": "system-design-rest",
        "domain": "system_design",
        "topic_id": "system-design.api-design",
        "title": "REST API Reference",
        "resource_type": "reference",
        "level": "beginner-intermediate",
        "duration": None,
        "url": "https://restfulapi.net/",
        "can_embed": False,
    },
    {
        "resource_id": "system-design-scalability",
        "domain": "system_design",
        "topic_id": "system-design.scalability",
        "title": "System Design Scalability",
        "resource_type": "article",
        "level": "beginner-intermediate",
        "duration": None,
        "url": "https://www.geeksforgeeks.org/system-design/system-design-scalability/",
        "can_embed": False,
    },
    {
        "resource_id": "system-design-load-balancing",
        "domain": "system_design",
        "topic_id": "system-design.load-balancing",
        "title": "Load Balancing",
        "resource_type": "article",
        "level": "beginner-intermediate",
        "duration": None,
        "url": "https://www.geeksforgeeks.org/system-design/load-balancing/",
        "can_embed": False,
    },
    {
        "resource_id": "system-design-primer",
        "domain": "system_design",
        "topic_id": "system-design.roadmap",
        "title": "System Design Primer",
        "resource_type": "reference",
        "level": "beginner-advanced",
        "duration": None,
        "url": "https://github.com/donnemartin/system-design-primer",
        "can_embed": False,
    },
    {
        "resource_id": "web-html-mdn",
        "domain": "web_dev",
        "topic_id": "web.html",
        "title": "MDN HTML Documentation",
        "resource_type": "documentation",
        "level": "beginner-advanced",
        "duration": None,
        "url": "https://developer.mozilla.org/en-US/docs/Web/HTML",
        "can_embed": False,
    },
    {
        "resource_id": "web-css-mdn",
        "domain": "web_dev",
        "topic_id": "web.css",
        "title": "MDN CSS Documentation",
        "resource_type": "documentation",
        "level": "beginner-advanced",
        "duration": None,
        "url": "https://developer.mozilla.org/en-US/docs/Web/CSS",
        "can_embed": False,
    },
    {
        "resource_id": "web-javascript-mdn",
        "domain": "web_dev",
        "topic_id": "web.javascript",
        "title": "MDN JavaScript Documentation",
        "resource_type": "documentation",
        "level": "beginner-advanced",
        "duration": None,
        "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
        "can_embed": False,
    },
    {
        "resource_id": "web-javascript-video",
        "domain": "web_dev",
        "topic_id": "web.javascript",
        "title": "JavaScript Full Course",
        "resource_type": "video",
        "level": "beginner",
        "duration": "3 hours",
        "url": "https://www.youtube.com/watch?v=PkZNo7MFNFg",
        "can_embed": True,
    },
    {
        "resource_id": "web-react-learn",
        "domain": "web_dev",
        "topic_id": "web.react",
        "title": "React Learn",
        "resource_type": "course",
        "level": "beginner-advanced",
        "duration": None,
        "url": "https://react.dev/learn",
        "can_embed": False,
    },
    {
        "resource_id": "web-node-learn",
        "domain": "web_dev",
        "topic_id": "web.node",
        "title": "Node.js Learn",
        "resource_type": "course",
        "level": "beginner-advanced",
        "duration": None,
        "url": "https://nodejs.org/en/learn",
        "can_embed": False,
    },
    {
        "resource_id": "web-fullstack-roadmap",
        "domain": "web_dev",
        "topic_id": "web.roadmap",
        "title": "Full Stack Roadmap",
        "resource_type": "roadmap",
        "level": "beginner-advanced",
        "duration": None,
        "url": "https://roadmap.sh/full-stack",
        "can_embed": False,
    },
]


def list_resources(
    domain: str | None = None,
    topic_id: str | None = None,
    level: str | None = None,
    resource_type: str | None = None,
    limit: int = 20,
) -> list[dict]:
    """Return curated resources matching the requested frontend filters."""
    results = RESOURCES
    if domain:
        results = [resource for resource in results if resource["domain"] == domain]
    if topic_id:
        results = [resource for resource in results if resource["topic_id"] == topic_id]
    if level:
        results = [resource for resource in results if level.lower() in resource["level"].lower()]
    if resource_type:
        results = [resource for resource in results if resource["resource_type"] == resource_type]
    return results[:limit]
